{
 "title": "Unit / Component / Integration Tracking",
 "time": { "from": "2022-02-11T09:59:53.482Z", "to": "2022-02-11T11:59:53.482Z" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repo",
    "query": "select distinct(repo) from track_commits"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "select distinct(branch) from track_commits where repo='$repo' "
   },
   {
    "name": "per_quarter",
    "label": "Per quarter",
    "query": "select distinct(per_quarter) from track_commits where repo='$repo' and branch='$branch' order by per_quarter desc"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Commits and Unit Tests Per Week in ${per_quarter} Quarter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  per_week as \"week\",\n  sum(total) as \"total\",\n  sum(require_unit_test) as \"required\",\n  sum(with_unit) as \"actual\"\nFROM public.track_commits\nWHERE repo = '${repo:raw}'\n  AND branch = '${branch:raw}'\n  AND per_quarter = '${per_quarter:raw}'\nGROUP BY per_week\nORDER BY per_week ASC\n"
    }
   ]
  },
  {
   "title": "Percentage of Commits that Required Unit Test in ${per_quarter} Quarter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(with_unit) as \"actual\"\nFROM track_commits\nWHERE\n  require_unit_test > 0\n  AND repo = '${repo:raw}'\n  AND branch = '${branch:raw}'\n  AND per_quarter = '${per_quarter:raw}'\n"
    }
   ]
  },
  {
   "title": "Percentage of Commits that Required Unit Test (All)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  per_quarter as \"quarter\",\n  avg(with_unit) as \"actual\"\nFROM public.track_commits\nWHERE require_unit_test > 0\n  AND repo = '${repo:raw}'\n  AND branch = '${branch:raw}'\nGROUP BY per_quarter\nORDER BY per_quarter"
    }
   ]
  },
  {
   "title": "Number of Commits and Unit Tests Per Quarter (All)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  per_quarter as \"quarter\",\n  sum(total) as \"total\",\n  sum(require_unit_test) as \"required\",\n  sum(with_unit) as \"actual\"\nFROM public.track_commits\nWHERE\n  repo = '${repo:raw}'\n  AND branch = '${branch:raw}'\nGROUP BY per_quarter\nORDER BY per_quarter ASC\n"
    }
   ]
  },
  {
   "title": "Percentage of Commits that Required Unit Test (including with E2E) (All)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  per_quarter as \"quarter\",\n  avg(with_test) as \"actual\"\nFROM public.track_commits\nWHERE require_unit_test > 0\n  AND repo = '${repo:raw}'\n  AND branch = '${branch:raw}'\nGROUP BY per_quarter\nORDER BY per_quarter"
    }
   ]
  }
 ]
}